# Generated by Django 5.0.6 on 2024-06-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'produto',
            },
        ),
    ]
