# Generated by Django 5.0.6 on 2024-06-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
    ]
