# Generated by Django 5.0.6 on 2024-06-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_produto_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='empresa',
            field=models.CharField(max_length=100),
        ),
    ]
