# Generated by Django 5.0.6 on 2024-06-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_produto_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaMaster',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cpf_nota', models.CharField(max_length=11)),
                ('troco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dinheiro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
