# Generated by Django 5.0.6 on 2024-06-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_vendamaster'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendamaster',
            table='vendas_master',
        ),
    ]
