# Generated by Django 5.0.6 on 2024-06-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_vendamaster_dinheiro_alter_vendamaster_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendamaster',
            name='dinheiro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendamaster',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendamaster',
            name='troco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
