# Generated by Django 5.0.6 on 2024-06-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_vendamaster_dinheiro_alter_vendamaster_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=100)),
                ('email1', models.EmailField(max_length=255, unique=True)),
                ('celular1', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='VendaDetalhe',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('qtd', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('qtd_devolvida', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'vendas_detalhe',
            },
        ),
    ]
