# Generated by Django 5.0.6 on 2024-06-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_pessoa_vendadetalhe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
