# Generated by Django 5.0.6 on 2024-06-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_pessoa_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vendadetalhe',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vendamaster',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
